同步上游到 5271e1f
RT-Thread-packages/nimble pull request #12
Opened 2021-11-23 08:30 UTC by greedyhao

2021-12-04 14:15 UTC, supperthomas requested changes

2021-12-04 14:15 UTC, supperthomas commented on README.md
> +# "License"); you may not use this file except in compliance
这个readme先保留以前的

2021-12-04 14:15 UTC, supperthomas commented on README.md
> +
建议readme 先保留以前的

2021-12-04 14:15 UTC, supperthomas commented on RELEASE_NOTES.md
> +If working on next-generation RTOS and Bluetooth protocol stack
可以略做补充AB等之类的

2021-12-06 02:12 UTC, supperthomas commented
+1

2021-12-06 02:16 UTC, greedyhao commented
ab32 那边先不管了吧，那边很多人用 studio 开发，用 studio 没法编译这边的 package。得等 studio 那边解决了这个问题再考虑怎么处理

2021-12-06 02:27 UTC, supperthomas commented
@armink 龙哥，帮忙加个tag。V1.0.后续latest版本持续更新。或者有更好的建议也可以提一下。

2021-12-08 01:41 UTC, merged