同步上游到 21d59b8b40c2 , 添加 RT-Thread UART 对接 HCI 层
RT-Thread-packages/nimble pull request #19
Opened 2022-07-18 03:29 UTC by Yanlineng

1. 同步上游到 21d59b8b40c2
2. 添加 RT-Thread UART 对接 HCI 层代码，路径： nimble/transport/rtthread/
3. 目前测试 QEMU 跑 Host端 搭配 外界蓝牙 Controller 卡片正常运行部分例程。
4. 添加 HCI 层相关编译构建选项

2022-07-18 05:49 UTC, supperthomas commented
- [ ] 部分例程。列一下测了具体几个例程。
- [ ] qemu搭配蓝牙的芯片具体型号写一下，或者搞一篇markdown文档放doc目录下面，作为user guider。提供蓝牙芯片的control的firmware，这个可以参考之前的github
- [ ]

2022-07-18 09:02 UTC, Yanlineng commented
1. BLE peripheral heartrate sensor
2. BLE peripheral cycling speed and cadence sensor
3. BLE central role sample
4. BLE peripheral role sample
5. BLE beacon sample
6. BLE advertiser sample
这六个例程可以运行，但 BLE peripheral role sample 貌似运行过程中有些小问题。

qemu 搭配蓝牙芯片相关，我稍后再补充一下。

2022-07-18 10:08 UTC, supperthomas commented
@Yanlineng 更新到上游代码大概需要修改了哪些可以列一下么？

2022-07-18 10:51 UTC, supperthomas commented
> 主要修改了 Host 和 Control 以及 Transport 目录下的代码
> 
> 1. HCI 层重构了，所以 Transport 目录下的代码基本都替换了，并且添加了 RT-Thread UART 对接代码
> 2. Host 和 Control 有一些官方自己调整，按照官方替换代码，然后 HCI 层框架在 Host 和 Control 代码中也有修改，这里也同步了。
> 3. npl 下 rt-thread 的对接代码是没改的
> 4. app 下例程源码沿用之前的版本，只是在运行时 debug，针对 Host 变化做了较小的更改，基本没变。
> 5. Sconscript 文件按照需求调整

整理一份简单的更新文档吧。列出哪些文件做了怎样的修改即可。下次别人可以照着更新到新的nimble。

2022-07-19 13:36 UTC, supperthomas requested changes

2022-07-19 13:38 UTC, supperthomas approved these changes

2022-07-19 13:41 UTC, merged